### ISSUE TITLE
LabelledAdjacencyMap?

### ISSUE THREAD

**Issue by o1lo01ol1o** [snowleopard/alga#109]
I have a case where I need to model a graph (of labeled edges) via an adjacency map representation (I need, among other things, to sort the graphs topologically and compute the cycles via `scc`).  It looks like the `Diode (Set e)` would take care of the labeling issue (my labels function only as edge identifiers) but I'm not sure what the best representation would be for the adjacency map itself given that I also need a King-Launchbury representation if I'm to avoid writing the sorts myself.  Could anyone advise?

**Comment by snowleopard** [comment]
Hi @o1lo01ol1o!

I think the implementation will be pretty similar to `Algebra.Graph.AdjacencyMap` but instead of

```haskell
Map a (Set a)
```

the labelled version will use

```haskell
Map a (Map a e)
```

as the underlying data structure (with edge labels of type `e`).

If you don't want to use dioids for labelling, then here is an alternative:

```haskell
Map a (Set (a, e))
```

Now instead of collapsing parallel edges using one of dioid's operations, you explicitly store each edge separately.

The former seems a bit more general, since one can always pick `e = Set e'` and obtain the latter.

Would you like to give it a try?

**Comment by snowleopard** [comment]
Thanks!

By the way, I think I was wrong in my previous comment when I said that one of the encodings is more general than the other -- they are actually equivalent in terms of generality. But one may be easier/faster to work with than the other.

**Comment by o1lo01ol1o** [comment]
See #113

**Comment by snowleopard** [comment]
After merging #113, we still need to do the following: 
- [ ] Add conversions between labelled and unlabelled adjacency maps
- [ ] Improve documentation
- [ ] Add tests

**Comment by snowleopard** [comment]
I think we can close this issue. See the module here:

https://hackage.haskell.org/package/algebraic-graphs/docs/Algebra-Graph-Labelled-AdjacencyMap.html
