### ISSUE TITLE
Maybe GraphIt can be a source of additional ideas?

### ISSUE THREAD

**Issue by ydewit** [snowleopard/alga#155]
Here is the link: http://graphit-lang.org

**Comment by snowleopard** [comment]
I haven't come across GhaphIt before -- it looks interesting. This line caught my attention:

> GraphIt separates what is computed (algorithm) from how it is computed (schedule)

I think we can say that the algebraic graph library separates the _meaning or structure of a graph_ (the syntax tree of the graph expression) from the _representation of a graph_ (adjacency map, matrix, etc.)

But I'm not sure what to do with this analogy :) To me, this library and GraphIt seem to be developed to solve different problems, but I may be wrong, since I know very little about GraphIt.

@ydewit Do you have anything specific in mind? Is there any GraphIt idea you'd like us to explore?

**Comment by snowleopard** [comment]
I'm going to close it since it's unclear what needs to be done, but feel free to reopen.
