### ISSUE TITLE
Add semiring instances for applicable types?

### ISSUE THREAD

**Issue by chessai** [snowleopard/alga#159]
I maintain a package called [semirings](https://github.com/chessai/semirings). It is on Hackage, Stackage, and nixpkgs. Its API is stable, and its support window is for GHC 7.4 and greater. The motivation behind this change is that a lot of Num instances carry with them the baggage of fromInteger, abs, and signum. To me, Num is just a crappy version of Ring. So, any types with Num instances here (or anywhere) could morally have Semiring and or Ring instances that are either equivalently lawful, equivalently unlawful, or less unlawful than their Num instances.

**Comment by snowleopard** [comment]
I fully agree that the `Num` typeclass is not ideal, and I'm looking forward to the day when we will have a proper type class hierarchy for semirings and rings in Prelude.

However, **algebraic graphs are not semirings**. They form a different algebraic structure, which I call "united monoids", because the two monoids have the same unit, i.e. `0 == 1` -- see more details in [this blog post](https://blogs.ncl.ac.uk/andreymokhov/united-monoids).

I abuse `Num` just for one reason: it gives me a very terse notation for constructing graphs, e.g. `1 * (2 + 3)`, which is very convenient for quick experiments in GHCi. Admittedly, using `Num` for this is a hack, but it is a very cheap one: there is no need to hide Prelude and depend on another library. Furthermore, note that this hack actually requires the `fromInteger` method of the `Num` typeclass! So if I switch to `semirings`, I will still need to create an instance for `Num`, which would be a mess :)

**Comment by chessai** [comment]
Yeah, I agree. I wasn't sure if there was any datatype here that was a valid semiring. In that case, I'll close this issue, since it seems like the change would be for the worse.

**Comment by snowleopard** [comment]
Actually, several valid semirings are defined in this module for edge labels:

https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/Label.hs

Right now I'm using a somewhat unusual definition for semirings, which differs from the one you use in your library:

```haskell
class Monoid a => Semiring a where
    one   :: a
    (<.>) :: a -> a -> a

zero :: Monoid a => a
zero = mempty

(<+>) :: Semigroup a => a -> a -> a
(<+>) = (<>)
```

This is useful because I want to allow edge labels that do not form full semirings, but only have a notion of parallel edge composition (which corresponds to the underlying additive monoid).

This part of the library is rather unstable, so I'm keeping things simple and do not plan to factor out any code into a separate library.

Have you ever thought about defining the `Semiring` type class like I do, by extending `Monoid`?

**Comment by chessai** [comment]
Yes, I have, and I don't think it makes sense. Having monoid as a superclass of semiring forces you to choose which structure to be the monoid. Also, just `Monoid` is a problem because it then _must_ be the multiplicative Monoid, since Monoids alone don't guarantee commutativity (For example, your zero/plus above don't make sense to me since Monoid isn't strong enough). Another problem with the superclass of Monoid is that you can't have a Semiring instance for things like `Int`, which is a totally fine instance.

**Comment by snowleopard** [comment]
Yes, I agree -- there are some issues with the current definition.

> Also, just `Monoid` is a problem because it then *must* be the multiplicative Monoid, since Monoids alone don't guarantee commutativity

Note that I currently require commutativity of `<+>` in the laws of the `Semiring` type class. So the only possible lawful definition is by using the additive monoid as `<+>` and multiplicative as `<*>`. I will probably add another intermediate type class in future: `Monoid => CommutativeMonoid => Semiring`. This will make a few type signatures (which currently require only `Monoid`) more precise.

> Another problem with the superclass of Monoid is that you can't have a Semiring instance for things like `Int`, which is a totally fine instance.

Indeed, this is a bit awkward. What one can do in this case is to wrap `Int` into a newtype. This is what I essentially do with the type `Count`, which also extends the underlying numeric type with positive infinity, so I can define the `StarSemiring` instance:

```haskell
data Extended a = Finite a | Infinite
    deriving (Eq, Functor, Ord, Show)

newtype NonNegative a = NonNegative (Extended a)
    deriving (Applicative, Eq, Functor, Ord, Monad)

newtype Count a = Count (Sum (NonNegative a))
    deriving (Bounded, Eq, Monoid, Num, Ord, Semigroup)

instance (Num a, Ord a) => Semiring (Count a) where
    one   = 1
    (<.>) = (*)

instance (Num a, Ord a) => StarSemiring (Count a) where
    star x | x == zero = one
           | otherwise = count infinite
```

The above code is somewhat tedious, but I found the resulting `Count` easy to use.

**Comment by chessai** [comment]
An issue I take with classes like `CommutativeMonoid` is that subclass/superclass hierarchies become brittle. What about CommutativeSemigroup? Should that too be a superclass of CommutativeMonoid? A package that comes to mind is [numhask](https://hackage.haskell.org/package/numhask). IMO typeclasses don't play well with numeric hierarchies, unless you constraint yourself to a small enough set of them - otherwise, the hierarchy becomes brittle quite easily. 

> Indeed, this is a bit awkward. What one can do in this case is to wrap Int into a newtype.

This was something I wanted to avoid while writing `semirings`, since newtypes introduce API overhead, are something mentioned now and then as a problem for things like `Monoid` (eg Sum, Int), and are often dissatisfying when introduced for the sole purpose of instance semantics (but most other introductions are fine.)

> which also extends the underlying numeric type with positive infinity, so I can define the StarSemiring instance:

You can use Data.Semiring.Tropical for this: https://hackage.haskell.org/package/semirings-0.3.1.1/docs/Data-Semiring-Tropical.html#t:Tropical
