### ISSUE TITLE
Acyclic graphs with Int labels

### ISSUE THREAD

**Issue by dschrempf** [snowleopard/alga#264]
As it happens to be, I am in the need of `Algebra.Graph.Acyclic.AdjacencyIntMap`, which is not yet in the library. I know, one cannot provide a specialized data structure for all possible use cases, but maybe you want to think about it. It is, at the very least, useful to me :)) !

Thanks,
Dominik

By the way, I think it would be useful if it was stated that all graphs in this library are __directed__, or are they not?

**Comment by snowleopard** [comment]
@dschrempf Oh no, the library seems to be in a state of continuous combinatorial explosion :-)

Of course, your feature request is perfectly sensible, but I have to admit I'm a bit terrified about the direction we are taking. Maintaining the Cartesian product of the following flavours seems infeasible:
* polymorphic vs specialised to `Int` vertices;
* possibly empty vs non-empty;
* possibly cyclic vs acyclic;
* algebraic vs adjacency maps;
* unlabelled vs labelled;
* directed vs undirected;
* reflexive vs not-necessarily reflexive;
* transitive vs non-transitive;
* general vs bipartite.

I'm not kidding, we have all of the above. That's 2^9=512 possible variants 😱 

So, I'm not sure what to say. On the one hand, I'm happy to review a PR implementing this new module, but on the other hand, I make no promises that I will have the patience of maintaining it (as well as all other modules) forever. We should clearly find a way to reduce the combinatorial explosion, somehow, but I don't see a way at the moment.

And yes, we do have undirected graphs in the library. See these three modules:

* [Algebra.Graph.Undirected](http://hackage.haskell.org/package/algebraic-graphs-0.5/docs/Algebra-Graph-Undirected.html)
* [Algebra.Graph.Relation.Symmetric](http://hackage.haskell.org/package/algebraic-graphs-0.5/docs/Algebra-Graph-Relation-Symmetric.html)
* [Algebra.Graph.Bipartite.Undirected.AdjacencyMap](http://hackage.haskell.org/package/algebraic-graphs-0.5/docs/Algebra-Graph-Bipartite-Undirected-AdjacencyMap.html)

**Comment by dschrempf** [comment]
Thank you for your reply.

That's what I expected :), I don't _really_ need the mentioned module; but it
may be a little faster than what I am using at the moment (and I do a lot of
number crunching).

In fact, as a user, I prefer a library with well maintained, neatly arranged
core features to an over-bloated library with mediocre maintenance.

With respect to the directed/undirected issue. I asked, because these words are
not mentioned much in the documentation. Actually, I had to fire up an
interactive session and test two graphs for equality to see if they are directed
or not. Maybe we should (I should) add a sentence or two about that.

**Comment by snowleopard** [comment]
>  I don't _really_ need the mentioned module; but it may be a little faster than what I am using at the moment (and I do a lot of number crunching).

It would be interesting to know how much performance you lose because of using generic adjacency maps in your application. While we do some benchmarks (https://github.com/haskell-perf/graphs), they are mostly synthetic. If you could add some real-world examples to the benchmarking suite that would be great and we could use it to guide our performance optimisation efforts. (Using `Int`-specialised data structures is not the only way to achieve that.)

> In fact, as a user, I prefer a library with well maintained, neatly arranged core features to an over-bloated library with mediocre maintenance.

I fully agree.

> With respect to the directed/undirected issue. I asked, because these words are
not mentioned much in the documentation. Actually, I had to fire up an
interactive session and test two graphs for equality to see if they are directed
or not. Maybe we should (I should) add a sentence or two about that.

I agree that a sentence on top of the module, clarifying that the graphs are directed,  would be useful. Feel free to send a PR but I might also look into doing this soon.

**Comment by dschrempf** [comment]
For the sake of it, I just refactored `Algebra.Graph.Labelled.AdjacencyMap` to use `Int` labels and `IntMap`, and the speedup is more a less a factor of 2.

**Comment by snowleopard** [comment]
@dschrempf Many thanks for sharing your results! 

By the way, there is one subtlety about `IntMap`: the complexity of its `size` function is [O(n)](https://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-IntMap-Internal.html#v:size) rather than just [O(1)](https://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Map-Internal.html#v:size) in the case of `Map`. It's easy to miss this fact during refactoring but it may be important for some applications.
