### ISSUE TITLE
Proposal : foldgM

### ISSUE THREAD

**Issue by ocramz** [snowleopard/alga#299]
How about adding a monadic fold ?

```Haskell
foldgM :: Monad m =>
          m b -- ^ empty
       -> (a -> m b) -- ^ vertex
       -> (b -> b -> m b) -- ^ overlay
       -> (b -> b -> m b) -- ^ connect
       -> G.Graph a
       -> m b
foldgM e v o c = go
  where
    go G.Empty         = e
    go (G.Vertex  x  ) = v x
    go (G.Overlay x y) = do
      a <- go x
      b <- go y
      o a b
    go (G.Connect x y) = do
      a <- go x
      b <- go y
      c a b
```

**Comment by snowleopard** [comment]
If we factor out the common code snippet in the overlay and connect branches of your implementation, we can get this:

```haskell
lift :: Monad m => (a -> b -> m c) -> (m a -> m b -> m c)
lift f ma mb = do
    a <- ma
    b <- mb
    f a b

foldgM :: Monad m =>
          m b -- ^ empty
       -> (a -> m b) -- ^ vertex
       -> (b -> b -> m b) -- ^ overlay
       -> (b -> b -> m b) -- ^ connect
       -> Graph a
       -> m b
foldgM e v o c = foldg e v (lift o) (lift c)
```

Strangely, `lift` doesn't seem to be a very common monadic combinator and so doesn't exist in the standard libraries.

Still, the fact that `foldgM` is easily expressible in terms of `foldg` suggests to me that it's not worth the work required to include it in `algebraic-graphs`. If anything, I think I'd prefer to move in the opposite direction and make the API smaller, to make it easier to maintain the library and develop some new interesting features. (Right now, doing any work on the library seems pretty overwhelming to me because of how much stuff is already there.)

**Comment by ocramz** [comment]
> I'd prefer to move in the opposite direction and make the API smaller, to make it easier to maintain the library and develop some new interesting features

Completely agree! I'll close this then.
