### ISSUE TITLE
exportviaShow might collapse vertices where (show v1) == (show v2) but v1 ≠ v2

### ISSUE THREAD

**Issue by jmtd** [snowleopard/alga#53]
Consider

```
import Algebra.Graph
import Algebra.Graph.Export.Dot
data SillyList = Slist Int Char deriving (Ord,Eq)
instance Show SillyList where
    show (Slist _ c) = show c
v0 = (Slist 0 'a')
v1 = (Slist 1 'a')
v2 = (Slist 2 'b') 
v3 = (Slist 3 'c')
g = path [v0,v1,v2,v3]
```
`exportViaShow g` results in:

![err](https://user-images.githubusercontent.com/63694/37307248-33a45900-2632-11e8-80fc-a9a25b42416d.png)

But we want

![yes](https://user-images.githubusercontent.com/63694/37307464-fb027f7c-2632-11e8-9c55-0c0d47b1250d.png)

In graphviz language this is achieved by unique node IDs but labelling them with the `show` value e.g. `0 [label="a"]` (although the hard part here is choosing unique node ID values per vertex for arbitrary types)

**Comment by snowleopard** [comment]
I'd say this is the right behaviour. Your `instance Show` breaks the unstated (but generally agreed upon) requirement for `Show` instances: if `show x == s` then it must be possible to feed `s` to a Haskell compiler and obtain `x` back. This might seem like a strange requirement, but it's very useful when you want to `show` a Haskell expression and use the result as a real Haskell code.

This requirement is often violated, but I'd advise against this, because some useful libraries (for example, Facebook's Haxl) rely on it to generate Haskell code.

Note that a consequence of this requirement is that `show` should be an injective (or one-to-one) function, which guarantees that this issue will not occur.

If you want to obtain the second graph, you need to use the `export` function instead, where you are in full control of how labels are assigned.

**Comment by snowleopard** [comment]
@jmtd I'm convinced the current behaviour is correct, so I'm closing this issue. Feel free to reopen if you'd like to argue that something should be changed.
